### PR TITLE
[v2] Fix Fabric 7 compiler errors related to autobind and TextField#onChanged

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
Fix Fabric 7.x compiler errors due to `autobind` and `TextField.onChanged` usage that has been deprecated and removed in Fabric 7.

This is a manual rebase of the changes in https://github.com/SharePoint/sp-starter-kit/pull/371 to `v2` branch.

### Before

```shell
[14:23:19] Finished subtask 'tslint' after 8.31 s                                                                                                               }
[14:23:19] Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(12,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(138,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(150,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/extensions/collabFooter/CollabFooterApplicationCustomizer.ts(20,55): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/extensions/collabFooter/components/CollabFooter.tsx(10,95): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(12,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/Utilities"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(130,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(142,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(154,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(5,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(65,21): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/extensions/portalFooter/components/PortalFooter/PortalFooter.tsx(11,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/webparts/followedSites/components/FollowedSites.tsx(170,28): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(11,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
[14:23:19] Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(194,25): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
[14:23:19] Error - 'tsc' sub task errored after 8.38 s 
 exited with code 2
[14:23:19] 'bundle' errored after 10 s
[14:23:19] 
[14:23:20] ==================[ Finished ]==================
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(12,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(138,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/common/myLinks/MyLinksDialog.tsx(150,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/collabFooter/CollabFooterApplicationCustomizer.ts(20,55): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/collabFooter/components/CollabFooter.tsx(10,95): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(12,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/Utilities"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(130,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & 
ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(142,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & 
ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/DateTimePicker.tsx(154,27): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & 
ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(5,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/extensions/discussNow/components/ScheduleMeetingDialog.tsx(65,21): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/extensions/portalFooter/components/PortalFooter/PortalFooter.tsx(11,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/webparts/followedSites/components/FollowedSites.tsx(170,28): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes & 
ITextFieldProps & { children?: ReactNode; }'.
Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(11,3): error TS2305: Module '"~/sp-starter-kit/solution/node_modules/office-ui-fabric-react/lib/index"' has no exported member 'autobind'.
Error - [tsc] src/webparts/lobIntegration/components/LobIntegration.tsx(194,25): error TS2339: Property 'onChanged' does not exist on type 'IntrinsicAttributes 
& ITextFieldProps & { children?: ReactNode; }'.
Error - 'tsc' sub task errored after 8.38 s 
 exited with code 2
[14:23:20] Project sp-starter-kit version:1.5.4
[14:23:20] Build tools version:3.12.1
[14:23:20] Node version:v10.18.1
[14:23:20] Total duration:15 s
[14:23:20] Task errors:16
```

cc: @johnguy0 @patmill

### CODE REVIEW

**Comment by eoverfield** [comment]
Thank you @KevinTCoughlin, the change to arrow functions is great, Im glad to see us remove autobind. Changing onChanged to onChange, do you see this causing any issues with SPFx 1.4 as we need to keep to that version for SP2019 within this source for now. Any hesitations?

**Comment by KevinTCoughlin** [comment]
> Thank you @KevinTCoughlin, the change to arrow functions is great, Im glad to see us remove autobind.

No problem @eoverfield. A positive side-effect of removing the `autobind` decorator is that we save bytes which is always good.

> Changing onChanged to onChange, do you see this causing any issues with SPFx 1.4 as we need to keep to that version for SP2019 within this source for now. Any hesitations?

If the solutions must work with SPFx 1.4 which references `office-ui-fabric-react@5.21.0` then we cannot merge the `TextField.onChanged` refactor. `office-ui-fabric-react@5.21.0` predates the introduction of `TextField.onChange` in https://github.com/OfficeDev/office-ui-fabric-react/pull/5764.

However, I'm a bit confused since this repo's `/solutions` lockfile references SPFx 1.9 packages and thus `office-ui-fabric-react@6.189.2` which contains the `TextField.onChange` API.

https://github.com/SharePoint/sp-starter-kit/blob/5708109cb6bd055a719c0125aaee194a9334767e/solution/package-lock.json#L2546

Do we advocate folks downgrade the relevant SPFx packages after cloning for SP2019?

Are there no compiler errors present with that downgrade which also downgrades `office-ui-fabric-react` from `6.189.2` to `5.21.0`?

Let's hold off on merging until I better understand the workflow here. Thanks for raising awareness. My concern is loose version selectors in this repo may bring in `office-ui-fabric-react@7.x` once this repo is pinned to SPFx 1.10 package suite.

**Comment by eoverfield** [comment]
@KevinTCoughlin Thank you for the PR, this tested out fine for the existing global solution found in /solution/src.

We will also want the autobind changes made to the new split out v2 solutions in the /source/"component". 

The v2 branch is primarily here to give us an area to split out each component into their own solution, downgrade to 1.4 so that they are SP2019 ready. You can see all of these in the /source folder.

In /solution/src, as you noticed, this was 1.9.1, this PR bumped to 1.10. Great.
While in /source, most all solutions are stuck at 1.4 for SP2019.

An upcoming step is to consider how to correctly maintain only one codebase for all components, i.e. not have /solution/src and /source, though that is a discussion for another day.

Thank you again.
