### ISSUE TITLE
portalFooter extension from the sp-starter-kit solution doesn't build separately.

### ISSUE THREAD

**Issue by Ashutosh2019** [SharePoint/sp-starter-kit#276]
#### Category
- [ ] Bug

#### Expected or Desired Behavior

When you extract one extension (portalFooter) from the sp-starter-kit solution and do a gulp serve after npm install the standalone solution build.

#### Observed Behavior

When you extract one extension (portalFooter) from the solution and try it gulp serve after npm install the build shows below error:

node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,124): error TS1005: ')' expected.
node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,177): error TS1005: '(' expected.
node_modules/@uifabric/foundation/lib/ISlots.d.ts(68,185): error TS1005: ':' expected.
node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(18,67): error TS1005: ';' expected.
node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(18,114): error TS1005: '(' expected
node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(18,136): error TS1005: '(' expected
src/extensions/portalFooter/loc/myStrings.d.ts(11,1): error TS1128: Declaration or statement expected

#### Steps to Reproduce

download the solution and take portal footer extension add required npm packages. Also add the associated assets and build. The solution shows error in the node modules uifabric.

Thanks for your contribution! Sharing is caring.

**Comment by bcameron1231** [comment]
Did the original starter kit solution build fine for you before extraction? These errors are similar errors you would receive if you had a TypeScript version  mismatch.

**Comment by Ashutosh2019** [comment]
you are correct the TypeScript version mismatch creates this problem

**Comment by Ashutosh2019** [comment]
TypeScript version mismatch creates this problem
